### ISSUE TITLE
Plugin sollte immer offen bleiben

### ISSUE THREAD

**Issue by studio255** [idiomReplaceX/idiomreplacex-client#1]
Aktuell schließt sich das Plugin nach dem Klick auf einen Link. Es sollte nach dem Aktivieren immer offen bleiben.

**Comment by akohlbecker** [comment]
dieses ticket gehört zu idiomReplaceX/idiomReplaceX-browser-extension

**Comment by akohlbecker** [comment]
moved: https://github.com/idiomReplaceX/idiomReplaceX-browser-extension/issues/1
