### ISSUE TITLE
send URL of webpage to filter service to allow identify all filter requests for the same page

### ISSUE THREAD

**Issue by akohlbecker** [idiomReplaceX/idiomreplacex-client#3]

**Comment by akohlbecker** [comment]
implemented with 73b75e8

**Comment by studio255** [comment]
Ich habe das Script nochmals auf den Server geladen, aber der Parameter "documentUrlId" kommt im Request nicht vor. Was mache ich falsch? Müsste doch auf der Ebene von html erscheinen, oder?

**Comment by studio255** [comment]
Parameter wurde gefunden, vermutlich ein Cache Problem. Sorry
